" Misc {{{

set modelines=1            " last line
set encoding=utf-8

" }}}
" Enhancement {{{

set nocompatible                " unleash vim's power
set backspace=indent,eol,start  " aggresive backspace
set path+=**                    " enable fuzzy search subdirectories

" }}}
" Visual {{{

color dracula
set background=dark
set number                 " show line numbers
set relativenumber         " show relative line number
set showcmd                " show command in bottom bar
set wildmenu               " visual autocomplete for command menu
set showmatch              " highlight matching [{()}]
set incsearch              " search as characters are entered
set hlsearch               " highlight matches
set cursorline             " highlight cursor line
filetype on                " enable file type detection
filetype indent on         " load filetype-specific indent files
syntax enable              " enable syntax highlighting
let python_highlight_all=1 " enable all Python syntax highlighting features

" change cursor for different mode
let &t_SI = "\<Esc>]50;CursorShape=1\x7"
let &t_SR = "\<Esc>]50;CursorShape=2\x7"
let &t_EI = "\<Esc>]50;CursorShape=0\x7"

" }}}
" Tab {{{

set softtabstop=4          " number of spaces in tab when editing
set tabstop=4              " number of visual spaces per TAB
set expandtab              " expand tabs into spaces
set autoindent             " indent when moving to the next line
set shiftwidth=4           " when using the >> or << commands, shift lines by 4 spaces

" }}}
" Folding {{{

set foldenable             " enable folding
set foldlevelstart=10      " open most folds by default
set foldnestmax=10         " 10 nested fold max
set foldmethod=indent      " fold based on indent level

" }}}
" Key Mapping {{{

" Change leader key
let mapleader=","       

" Substitube highlighted text
nnoremap <leader>r :%s///g<left><left>

" Clear search highlight
nnoremap <leader><space> :nohlsearch<CR>:echo "Search cleared"<CR>

" Fold/unfold
nnoremap <space> za                      

" Move to line start/end
nnoremap B ^
nnoremap E $

" Run as python script
autocmd FileType python nnoremap <buffer> <F9> :exec '!clear; python' shellescape(@%, 1)<cr>

" Navigate among buffers
nnoremap <silent> [b :bprevious<CR>
nnoremap <silent> ]b :bnext<CR>
nnoremap <silent> [B :bfirst<CR>
nnoremap <silent> ]B :blast<CR>

" }}}
" Snippets {{{

nnoremap ,html :-1read $HOME/.vim/snippets/_skeleton.html<CR>3jwf>a

" }}}
" NERDTree {{{

" Ignore files in NERDTree
let NERDTreeIgnore=['\.pyc$', '\~$'] 
" Toggle 
nnoremap <c-n> :NERDTreeToggle<CR>
" Open with current file
nnoremap <silent> <leader>f :NERDTreeFind<CR>
" Auto quit vim when NERDTree is the only buffer
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

" }}}

" vim:foldmethod=marker:foldlevel=0
